# Native R Travis Github
language: r
sudo: required
cache: packages

# Build and check
install:
  - Rscript -e 'install.packages("devtools");devtools::install_deps("BioMark")'
script:
  - Rscript -e 'devtools::check("BioMark")'

notifications:
  email:
    on_success: change
    on_failure: change
